import "../css/left.css"
import "../css/right.css"
import "../css/portfolio.css"
import "./all_style.css"
import "../about_me/css/about-me.css"
import "../about_me/css/right.css"
import "../contact_me/css/contact-me.css"
import "../contact_me/css/right.css"
import "../contact_me/css/footer.css"
// import "bootstrap/dist/css/bootstrap.min.css"

